name: reinvent
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.2
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - apted==1.0.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - blinker==1.9.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - chemprop==1.5.2
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - descriptastorus==2.8.0
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - exceptiongroup==1.3.1
      - filelock==3.20.3
      - flask==3.1.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - funcy==2.0
      - future==1.0.0
      - grpcio==1.76.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - idna==3.11
      - imagesize==1.4.1
      - iniconfig==2.3.0
      - isim==15.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - llvmlite==0.46.0
      - lmdb==1.7.5
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mmpdb==2.1
      - molvs==0.1.1
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numba==0.63.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - openeye-toolkits==2025.2.1
      - packaging==25.0
      - pandas==2.3.3
      - pandas-flavor==0.8.1
      - pillow==10.4.0
      - pluggy==1.6.0
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pumas==1.3.0
      - py4j==0.10.9.9
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pytest==8.4.2
      - pytest-mock==3.15.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2025.9.3
      - regex==2026.1.15
      - reinvent==4.7.15
      - requests==2.32.5
      - requests-mock==1.12.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - snowballstemmer==3.0.1
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sympy==1.14.0
      - tenacity==8.5.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.9.1
      - torch-geometric==2.7.0
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.6
      - triton==3.5.1
      - typed-argument-parser==1.11.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - unimol-tools==0.1.5
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - xarray==2025.6.1
      - xxhash==3.6.0
      - yarl==1.22.0
