[io]
smiles_file = "data/2M.csv"
model_file = "lohc_2M.model"

[network]
num_layers = 3
layer_size = 512
dropout = 0.0
layer_normalization = false
standardize = true

[metadata]
data_source = "data/2M.csv"
comment = "Model created from data/2M.csv"
