# For All DeepChem scoring, the params should MATCH the ckpt files, otherwise would BREAK, do not adjust hyperparameters
# just set as -1
type = "geometric_mean"
parallel = 1
# set parallel = 1 for cpu runtime 

### DE ###


[[component]]
[component.DeepChemDMPNN]
[[component.DeepChemDMPNN.endpoint]]
name = "Dehydrogenation Enthalpy"
# # Adjust weights for multiple guiding with RL
weight = 0.45
params.checkpoint_path = "generate/dc_ckpt/de.ckpt"
params.transformer_path = "generate/chkpt/y_transformer/de.joblib"
params.device = "cpu"
params.batch_size = 64
params.features_generators = "rdkit_desc_normalized"
params.depth = -1
params.ffn_hidden = -1
params.ffn_layers = -1
params.dropout_p = -1
params.bias = true
params.global_features_size = -1
# double_sigmoid = window target
transform.type = "double_sigmoid"
# # set low and high for target DE value
transform.low = 40.0
transform.high = 70.0
# # coef_div, symmetric slope, inverse proportional
transform.coef_div = 300.0
# # coef_si, lower value edge slope, proportional
transform.coef_si = 150.0
# # coef_se, higher value edge slope, proportional
transform.coef_se = 150.0

### MP Melting Point ###
[[component]]
[component.MPP]

[[component.MPP.endpoint]]
name = "Melting point from the MPP model"
weight = 0.45

params.checkpoint_path = "generate/chkpt/mpp.ckpt"
params.device = "cpu"
params.batch_size = 64
params.num_workers = 0
params.max_length = 200
params.img_dim = 256
params.tokenizer_name = "DeepChem/ChemBERTa-77M-MLM"
params.output_index = 0

# # Optional transform (uncomment and tune for your property range)
transform.type = "ExponentialDecay"
transform.m = 300
# 300 kelvin or celsius
transform.k = 0.5


### caph2 ###


# TODO caph2


### SA ###


[[component]]
[component.SAScore]
[[component.SAScore.endpoint]]
name = "Synthetic Accessibility score"
weight = 0.1
transform.type = "reverse_sigmoid"
transform.low = 1
transform.high = 10
transform.k = 0.3
