run_type = "staged_learning"
device = "cuda:0"  
json_out_config = "log/json_out" 
tb_logdir = "log"
seed = 42

[parameters]
prior_file = "priors/reinvent.prior"
agent_file = "priors/reinvent.prior"
summary_csv_prefix = "multi_RL_1_6_test"
use_checkpoint = "false"
purge_memories = "true"
# smiles_file = "<path/to/SMILES>"
batch_size = 100
randomize_smiles = true
# to remove redundancies in the generated smiles
unique_sequences = true
temperature = 1.0
sample_strategy = "multinomial"
# sample_strategy = "beamsearch"

[learning_strategy]
type = "dap"
sigma = 128
rate = 0.0001

[diversity_filter]
type = "ScaffoldSimilarity"
# type = "PenalizeSameSmiles"
bucket_size = 25
minscore = 0.4
minsimilarity = 0.4
# # For PenalizeSameSmiles
# penalty_multiplier = 0.5

[inception]
# # May add good smiles here to seed memory
# smiles_file = "generate/incept/<file_name>"
# memory_size = 50
# sample_size = 10

[[stage]]
# # First stage for de, logd, sa score 
max_steps = 10000
# # Mind the scoring function and adjust max_score accordingly
max_score = 1.0
min_steps = 50
termination = "simple"
chkpt_file = "generate/chkpt/<chkpt_file_name>"

[stage.diversity_filter]
# # Add diversity filters from [diversity_filter] that is specific to this stage

[stage.scoring]
# [stage.scoring] can reference external scoring file
file_name = "configs/de_logd_ws_sa.toml"
file_type = "toml"




