input_csv_file = "2M_lohc.smi"
output_smiles_file = "2M.smi"
smiles_column = "smiles"  # Adjust if your CSV has a header, otherwise this is ignored for raw files
separator = " "           # Adjust if your file is not comma-separated
num_procs = 1
chunk_size = 10000


# Recommended settings
keep_isotope_molecules = true  # Keep [13C] etc.
keep_stereo = true             # Keep @, @@
uncharge = true                # Neutralize charges
transforms = ["standard"]      # Apply standard normalizations
